const SEARCH_FOCUSED = 'SEARCH_FOCUSED'
const SEARCH_BLUR = 'SEARCH_BLUR'
const CHANGE_LIST = 'CHANGE_LIST'
const ONMOUSEENTER = 'header/ONMOUSEENTER'
const ONMOUSELEAVE = 'header/ONMOUSELEAVE'
const CHANGE_PAGE = 'header/CHANGE_PAGE'
export {SEARCH_BLUR, SEARCH_FOCUSED, CHANGE_LIST, ONMOUSELEAVE, ONMOUSEENTER, CHANGE_PAGE}