const SWITCH_WRITER_PAGE = 'HOME/SWITCH_WRITER_PAGE'
const INIT_HOME_PAGE_DATA = 'HOME/INIT_HOME_PAGE_DATA'
const GET_MORE_LIST_INFO = 'HOME/GET_MORE_LIST_INFO'
const TOGGLE_SCROLL = 'HOME/TOGGLE_SCROLL'
export {SWITCH_WRITER_PAGE, INIT_HOME_PAGE_DATA, GET_MORE_LIST_INFO, TOGGLE_SCROLL}